# Generated by Django 5.2.8 on 2025-11-06 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slot', models.CharField(choices=[('09_11', '09:00–11:00'), ('11_13', '11:00–13:00'), ('13_15', '13:00–15:00'), ('15_17', '15:00–17:00'), ('17_19', '17:00–19:00')], max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='technicians.technician')),
            ],
            options={
                'unique_together': {('technician', 'date', 'slot')},
            },
        ),
    ]
