# Generated by Django 5.2.8 on 2025-11-06 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('09_11', '09:00–11:00'), ('11_13', '11:00–13:00'), ('13_15', '13:00–15:00'), ('15_17', '15:00–17:00'), ('17_19', '17:00–19:00')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Customer Booking',
                'verbose_name_plural': 'Customer Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
