# Generated by Django 5.2.8 on 2025-11-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('before_total_km', models.FloatField()),
                ('after_total_km', models.FloatField()),
                ('distance_saved_km', models.FloatField()),
                ('groups_optimized', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Assignment Run',
                'verbose_name_plural': 'Assignment Runs',
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['city', 'date'], name='bookings_as_city_9b0e00_idx'), models.Index(fields=['-run_at'], name='bookings_as_run_at_5cd4cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_pincode', models.CharField(max_length=10)),
                ('old_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('new_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('old_km', models.FloatField()),
                ('new_km', models.FloatField()),
                ('delta_km', models.FloatField()),
                ('changed', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_changes', to='bookings.customerbooking')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='bookings.assignmentrun')),
            ],
            options={
                'verbose_name': 'Assignment Change',
                'verbose_name_plural': 'Assignment Changes',
                'ordering': ['run', 'slot', 'customer_name'],
                'indexes': [models.Index(fields=['run', 'changed'], name='bookings_as_run_id_9f68c8_idx')],
            },
        ),
    ]
